version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:14.15.0
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/bitnami/postgresql"
    environment:
      - POSTGRES_PASSWORD=postgres


volumes:
  postgres:
