version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:14.15.0
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/bitnami/postgresql"
    environment:
      - POSTGRES_PASSWORD=postgres

  redpanda:
    container_name: redpanda
    command:
      - redpanda
      - start
      - '--smp'
      - '1'
      - '--reserve-memory'
      - 0M
      - '--overprovisioned'
      - '--node-id'
      - '0'
      - '--kafka-addr'
      - 'PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092'
      - '--advertise-kafka-addr'
      - 'PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092'
    image: 'redpandadata/redpanda:v23.2.8'
    ports:
      - '9092:9092'
      - '29092:29092'

  console:
    container_name: console
    image: 'redpandadata/console:v2.3.1'
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        connect:
          enabled: true
          clusters:
            - name: datagen
              url: http://connect:8083
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Interface web
      - "1025:1025"  # Porta SMTP
    restart: unless-stopped

volumes:
  postgres:
