server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: scheduler
  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  task:
    scheduling:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: scheduler-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
app:
  jwt:
    secret: 57ffd86ce5c53fccdfc26bd1153e825dcbda4f76d1587692689dd8b1e2b33285
    expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

geocoding:
  nominatim:
    base-url: https://nominatim.openstreetmap.org

