server:
  port: 8081

spring:
  application:
    name: scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 57ffd86ce5c53fccdfc26bd1153e825dcbda4f76d1587692689dd8b1e2b33285
    expiration: 86400000
