global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'scheduler'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'scheduler'

  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redpanda'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'prometheus'
