{
 "title": "Redpanda Dashboard",
 "tags": [
  "redpanda",
  "kafka"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tamanho dos Tópicos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (vectorized_cluster_partition_bytes_produced_total)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Taxa de Produção de Mensagens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgps" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(vectorized_cluster_partition_records_produced[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Taxa de Consumo de Mensagens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "msgps" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(vectorized_cluster_partition_records_fetched[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latência do Redpanda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vectorized_kafka_handler_latency_microseconds_sum[5m]) / rate(vectorized_kafka_handler_latency_microseconds_count[5m])",
     "legendFormat": "Latência Média"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vectorized_memory_allocated_memory / vectorized_memory_total_memory * 100",
     "legendFormat": "Uso de Memória"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(vectorized_reactor_cpu_busy_ms[5m]) * 100",
     "legendFormat": "Uso de CPU"
    }
   ]
  }
 ]
}