groups:
  - name: redpanda
    rules:
      - alert: RedpandaHighCPUUsage
        expr: rate(redpanda_cpu_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso alto de CPU no Redpanda"
          description: "Uso de CPU está acima de 80% nos últimos 5 minutos"

      - alert: RedpandaHighMemoryUsage
        expr: redpanda_memory_used_bytes / redpanda_memory_total_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso alto de memória no Redpanda"
          description: "Uso de memória está acima de 80%"

      - alert: RedpandaHighDiskUsage
        expr: redpanda_disk_used_bytes / redpanda_disk_total_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uso alto de disco no Redpanda"
          description: "Uso de disco está acima de 80%"

      - alert: RedpandaHighLatency
        expr: rate(redpanda_kafka_request_latency_seconds_sum[5m]) / rate(redpanda_kafka_request_latency_seconds_count[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Latência alta no Redpanda"
          description: "Latência média está acima de 100ms nos últimos 5 minutos"
